---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Gemfile. Gemfile.lock]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Angry Friends for Facebook! - Who unfriended me?"
keywords:    "safe, web, for, kids, control, content, restricted, filter, porn, nofap, blocker, child, limited, adult, access, best, app, mums, ios, whitelist"
description: "Have you ever wondered who deleted you on Facebook? Angry Friends will show you who unfriended you!"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-25289053-6 ## put YOUR key here to enable tracking! (blank to disable)
appstore_link: "https://itunes.apple.com/app/angry-friends-for-facebook/id1122583310?ct=web&mt=8"
# For example, my configuration is this:
url: https://test.bobgoo.com
enforce_ssl: test.bobgoo.com

twitter:
    card: app
    site: "@AngryFriendsApp"
    app:
        id: 460723131   

defaults:
  -
    scope:
      path: ""
    values:
        image:
            path: /img/Icon-Rounded-256.png
            #twitter: /img/Icon-Rounded-256.png
            facebook: /img/Icon-Rounded-256.png
            height: 256
            width: 256

  
### template colors, used site-wide via css ###
colors:
  red:       '#8E2223'      
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gtgold:    '#E0A01F'
  gtnavy:    '#01192F'
  gtmetallic: '#A08452'

kramdown:
  auto_ids:  false

gems:
  - jekyll-seo-tag